sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t raunakjodhawat/frontend:latest .

script:
    - docker run -e CI=true raunakjodhawat/frontend npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-681334850105"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_CODE
    secret_access_key: "$AWS_SECRET_KEY"
